[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

[dependencies]
binance-rs-async = { git = "https://github.com/Igosuki/binance-rs-async.git", features = ["margin_api"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
serde_json = "1.0.96"
chrono = "0.4.26"
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["full"] }
ta = "0.5.0"
rand = "0.8.5"
strum = "0.25"
strum_macros = "0.25"
getset = "0.1.2"
csv = "1.2.2"
egui = "0.22.0"
eframe = "0.22.0"
clap = "4.3.1"
serde_with = "3.0.0"
