[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

[dependencies]
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = "0.4"
futures = "0.3"
tokio = { version = "1.40", features = ["full"] }
ta = "0.5"
csv = "1.3"
thiserror = "1.0"
once_cell = "1.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "chrono",
    "time",
] }
tracing-appender = "0.2"
smartcore = { git = "https://github.com/smartcorelib/smartcore", branch = "development" }
linfa = "0.7"
linfa-pls = "0.7"
ndarray = "0.15"

[dev-dependencies]
tempfile = "3.13"
serial_test = "3.1"
