[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

[dependencies]
binance-rs-async = { git = "https://github.com/Igosuki/binance-rs-async.git", features = ["margin_api"] }
serde = { version = "1.0.166", features = ["derive", "rc"] }
serde_yaml = "0.9.22"
chrono = "0.4.26"
futures = "0.3.28"
tokio = { version = "1.29.1", features = ["full"] }
ta = "0.5.0"
getset = "0.1.2"
csv = "1.2.2"
clap = {version = "4.3.10", features = ["wrap_help", "derive"] }
thiserror = "1.0.40"
log = "0.4.19"
simple_logger = "4.2.0"