[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

[dependencies]
binance-rs-async = { git = "https://github.com/Igosuki/binance-rs-async.git", features = ["margin_api"] }
chrono = "0.4.30"
futures = "0.3.28"
tokio = { version = "1.32.0", features = ["full"] }
ta = "0.5.0"
getset = "0.1.2"
thiserror = "1.0.48"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"