[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-matrix = { path = "r-matrix" }
binance-r-matrix = { path = "binance-r-matrix" }
tokio = { version = "1.32.0", features = ["full"] }

[workspace]
members = [
    "r-matrix",
    "binance-r-matrix",
]