[package]
name = "krypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-matrix = { path = "r-matrix" }
binance-r-matrix = { path = "binance-r-matrix" }
tokio = { version = "1.32", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
getset = "0.1"
thiserror = "1.0"
serde_yaml = "0.9"
csv = "1.3"
bincode = "1.3"

[workspace]
members = ["r-matrix", "binance-r-matrix"]
