training-periods: 2000
testing-periods: 1000
interval: "30m"
depth: 1
margin: 5.0
trees: 20
seed: 3
fee: 0.027
function-multiplier: 100
function: "Softsign"
min-score: 0.0
tickers: 
  - "BTCUSDT"
  - "ETHUSDT"
  - "BNBUSDT"
  - "XRPUSDT"
  - "SOLUSDT"
  - "ADAUSDT"
  - "DOGEUSDT"
  - "TRXUSDT"
  - "MATICUSDT"
  - "DOTUSDT"
  - "LTCUSDT"
  - "BCHUSDT"
  - "SHIBUSDT"
  - "LINKUSDT"
  - "AVAXUSDT"
  - "XLMUSDT"
  - "XMRUSDT"
  - "ATOMUSDT"
  - "UNIUSDT"
  - "ETCUSDT"
  - "HBARUSDT"
  - "FILUSDT"