#!/usr/bin/env python3
"""Chart: CHAND_PERIOD hyperopt equity comparison.
Generated by: chand_period_hyperopt.rs
"""
import csv
import sys
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

EQUITY_CSV = 'snapshots/chand_period_equity_curves.csv'
CHART_PNG = 'charts/chand_period_comparison.png'
BASELINE_CP = 28
WINNER_CP = None  # filled in from command line or CSV header

def load_equity_csv(path):
    with open(path) as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        steps = []
        data = {}
        for row in reader:
            step = int(row['step'])
            steps.append(step)
            for col in cols:
                if col == 'step':
                    continue
                cp = col.replace('cp_', '')
                if cp not in data:
                    data[cp] = []
                data[cp].append(float(row[col]))
        return steps, data

def main():
    steps, data = load_equity_csv(EQUITY_CSV)
    if not steps:
        print('No data'); return

    # Determine winner from summary if not set
    global WINNER_CP
    if WINNER_CP is None:
        # Infer from equity curves — find max final value
        best_cp = None
        best_val = -999
        for cp, eq in data.items():
            if eq and eq[-1] > best_val:
                best_val = eq[-1]
                best_cp = cp
        if best_cp:
            WINNER_CP = int(best_cp)

    # Sort CP keys numerically
    cps = sorted(data.keys(), key=lambda x: int(x))
    if not cps:
        print('No CPs found'); return

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), sharex=False)
    fig.suptitle(f'CHAND_PERIOD Hyperopt — Equity Curves', fontsize=14, fontweight='bold')

    # Color map
    cm = plt.get_cmap('tab20')
    colors = {}
    for i, cp in enumerate(cps):
        colors[cp] = cm(i / max(len(cps)-1, 1))

    # Plot each CP
    for cp in cps:
        eq = data[cp]
        if not eq:
            continue
        label = f'CP={cp}'
        lw = 1.2
        if WINNER_CP is not None and int(cp) == WINNER_CP:
            label = f'CP={cp} [WINNER]'
            lw = 2.5
        elif int(cp) == BASELINE_CP:
            label = f'CP={cp} [BASELINE]'
            lw = 2.0
        ax1.plot(steps, eq, label=label, color=colors[cp], linewidth=lw, alpha=0.85)

    ax1.set_yscale('log')
    ax1.set_ylabel('Equity (log scale)')
    ax1.set_xlabel('Bar (daily)')
    ax1.set_title('Aggregated Equity (all universes)')
    ax1.legend(loc='upper left', fontsize=9)
    ax1.grid(True, alpha=0.3)
    ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:.1f}'))

    # Drawdown panel
    for cp in cps:
        eq = data[cp]
        if not eq:
            continue
        peak = 0.0
        dd_curve = []
        for e in eq:
            if e > peak:
                peak = e
            dd = (peak - e) / peak * 100.0
            dd_curve.append(dd)
        label = f'CP={cp}'
        lw = 1.2
        if WINNER_CP is not None and int(cp) == WINNER_CP:
            label = f'CP={cp} [WINNER]'
            lw = 2.5
        elif int(cp) == BASELINE_CP:
            label = f'CP={cp} [BASELINE]'
            lw = 2.0
        ax2.plot(steps, dd_curve, label=label, color=colors[cp], linewidth=lw, alpha=0.85)

    ax2.set_ylabel('Drawdown (%)')
    ax2.set_xlabel('Bar (daily)')
    ax2.set_title('Drawdown')
    ax2.legend(loc='lower left', fontsize=9)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(CHART_PNG, dpi=150, bbox_inches='tight')
    print(f'Saved: {CHART_PNG}')

if __name__ == '__main__':
    if len(sys.argv) > 1:
        WINNER_CP = int(sys.argv[1])
    main()
