[package]
name = "r-matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
futures = "0.3"
statrs = "0.16"