//! T76 — Binance taker-buy pressure feasibility check
//!
//! Binance daily klines include `taker_buy_quote_asset_volume`, which is a
//! public, no-auth order-flow proxy without downloading raw aggTrades.
//!
//! This example loads `data/cache/taker_buy/*_1d.parquet` generated by
//! `scripts/download_with_taker_buy.py` and tests whether daily taker-buy
//! pressure is a useful next-day predictor before wiring it into a full live
//! strategy harness.
//!
//! Guardrail: this is a signal feasibility check, not a promotion. T73 showed
//! the live bot depends on a small convex winner set, so any entry filter must
//! preserve those winners before promotion.

use anyhow::{Context, Result};
use polars::prelude::*;
use std::collections::BTreeMap;
use std::fs::File;

const SYMBOLS: &[&str] = &["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT"];
const CACHE_DIR: &str = "data/cache/taker_buy";
const OUT_PATH: &str = "snapshots/t76_taker_buy_pressure.md";

#[derive(Debug, Clone)]
struct Obs {
    time_ms: i64,
    pressure: f64,
    ret_next: f64,
}

#[derive(Debug, Clone)]
struct QuintileRow {
    q: usize,
    lo: f64,
    hi: f64,
    n: usize,
    avg_ret: f64,
    sharpe: f64,
}

fn load_symbol(symbol: &str) -> Result<Vec<Obs>> {
    let path = format!("{}/{}_1d.parquet", CACHE_DIR, symbol.to_lowercase());
    let df = ParquetReader::new(File::open(&path).with_context(|| format!("open {path}"))?)
        .finish()
        .with_context(|| format!("read parquet {path}"))?;

    let time = df.column("time_ms")?.i64()?;
    let close = df.column("close")?.f64()?;
    let pressure = df.column("taker_buy_pressure")?.f64()?;

    let mut out = Vec::with_capacity(df.height().saturating_sub(1));
    for i in 0..df.height().saturating_sub(1) {
        let (Some(t), Some(c0), Some(c1), Some(p)) = (
            time.get(i),
            close.get(i),
            close.get(i + 1),
            pressure.get(i),
        ) else {
            continue;
        };
        if c0 > 0.0 && p.is_finite() {
            out.push(Obs {
                time_ms: t,
                pressure: p,
                ret_next: c1 / c0 - 1.0,
            });
        }
    }
    Ok(out)
}

fn mean(xs: &[f64]) -> f64 {
    if xs.is_empty() { 0.0 } else { xs.iter().sum::<f64>() / xs.len() as f64 }
}

fn stddev(xs: &[f64]) -> f64 {
    if xs.len() < 2 { return 0.0; }
    let m = mean(xs);
    let var = xs.iter().map(|x| (x - m).powi(2)).sum::<f64>() / (xs.len() - 1) as f64;
    var.sqrt()
}

fn sharpe_daily(xs: &[f64]) -> f64 {
    let sd = stddev(xs);
    if sd <= 0.0 { 0.0 } else { mean(xs) / sd * 365.0_f64.sqrt() }
}

fn quantiles(obs: &[Obs]) -> Vec<QuintileRow> {
    let mut ps: Vec<f64> = obs.iter().map(|o| o.pressure).collect();
    ps.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let bounds: Vec<f64> = [0.2, 0.4, 0.6, 0.8]
        .iter()
        .map(|q| ps[((ps.len() as f64 - 1.0) * q).round() as usize])
        .collect();

    let ranges = vec![
        (0.0, bounds[0]),
        (bounds[0], bounds[1]),
        (bounds[1], bounds[2]),
        (bounds[2], bounds[3]),
        (bounds[3], 1.0),
    ];

    ranges
        .into_iter()
        .enumerate()
        .map(|(i, (lo, hi))| {
            let rets: Vec<f64> = obs
                .iter()
                .filter(|o| o.pressure >= lo && o.pressure < hi)
                .map(|o| o.ret_next)
                .collect();
            QuintileRow { q: i + 1, lo, hi, n: rets.len(), avg_ret: mean(&rets), sharpe: sharpe_daily(&rets) }
        })
        .collect()
}

fn main() -> Result<()> {
    println!("T76 — Binance taker-buy pressure feasibility check\n");

    let mut by_symbol = BTreeMap::new();
    for &symbol in SYMBOLS {
        let obs = load_symbol(symbol)?;
        println!("{}: {} observations", symbol, obs.len());
        by_symbol.insert(symbol, obs);
    }

    let mut report = String::new();
    report.push_str("# T76 — Binance Taker-Buy Pressure Feasibility\n\n");
    report.push_str("Binance daily klines expose taker-buy quote volume, giving a public no-auth order-flow proxy: `taker_buy_pressure = taker_buy_quote_vol / quote_vol`.\n\n");

    report.push_str("## Per-symbol next-day returns by taker-buy pressure quintile\n\n");
    report.push_str("| Symbol | Q | Pressure range | N | Avg next-day ret | Annualised Sharpe |\n");
    report.push_str("|---|---:|---:|---:|---:|---:|\n");

    for (&symbol, obs) in &by_symbol {
        for row in quantiles(obs) {
            report.push_str(&format!(
                "| {} | {} | {:.3}-{:.3} | {} | {:+.3}% | {:.2} |\n",
                symbol,
                row.q,
                row.lo,
                row.hi,
                row.n,
                row.avg_ret * 100.0,
                row.sharpe
            ));
        }
    }

    // Cross-sectional long high pressure / short low pressure feasibility.
    let mut panel: BTreeMap<i64, Vec<(&str, f64, f64)>> = BTreeMap::new();
    for (&symbol, obs) in &by_symbol {
        for o in obs {
            panel.entry(o.time_ms).or_default().push((symbol, o.pressure, o.ret_next));
        }
    }

    let mut cs_ls = Vec::new();
    let mut days = 0usize;
    for (_time, mut rows) in panel {
        if rows.len() < 5 { continue; }
        rows.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        let top: Vec<f64> = rows.iter().take(2).map(|r| r.2).collect();
        let bottom: Vec<f64> = rows.iter().rev().take(2).map(|r| r.2).collect();
        cs_ls.push(mean(&top) - mean(&bottom));
        days += 1;
    }

    let cs_mean = mean(&cs_ls);
    let cs_sharpe = sharpe_daily(&cs_ls);
    let cs_win = if cs_ls.is_empty() { 0.0 } else { cs_ls.iter().filter(|r| **r > 0.0).count() as f64 / cs_ls.len() as f64 };

    report.push_str("\n## Cross-sectional pressure spread\n\n");
    report.push_str(&format!(
        "Long top-2 pressure / short bottom-2 pressure across Base5: **{:+.3}%/day**, Sharpe **{:.2}**, win rate **{:.1}%**, N={} days.\n\n",
        cs_mean * 100.0,
        cs_sharpe,
        cs_win * 100.0,
        days
    ));

    report.push_str("## Verdict\n\n");
    report.push_str("- Taker-buy pressure is **real data we were throwing away**: the standard Binance kline response already contains the needed order-flow fields.\n");
    report.push_str("- Signal quality is **mixed by symbol**. BTC/XRP/DOGE show higher next-day returns at high pressure; ETH/SOL invert or flatten.\n");
    report.push_str("- Cross-sectional high-minus-low pressure has only a modest Sharpe, so this is not strong enough to promote as a Turtle entry filter.\n");
    report.push_str("- Use as future research input / feature cache, not as a production gate. Any candidate must still pass the T73 convex-winner preservation guardrail.\n");

    std::fs::write(OUT_PATH, &report)?;

    println!("\nCross-sectional Base5 pressure spread: {:+.3}%/day, Sharpe {:.2}, win {:.1}% (N={})",
        cs_mean * 100.0, cs_sharpe, cs_win * 100.0, days);
    println!("Report written: {}", OUT_PATH);

    Ok(())
}
