#!/usr/bin/env python3
"""Generate HALL_OF_FAME.md from the exact live-bot source-of-truth report.

T67 rule: production-facing headline metrics must come from
`snapshots/live_bot_exact_equity.md` only. Research harness and walk-forward
Sharpe numbers are diagnostics, not production account performance.
"""

from pathlib import Path
import datetime as dt
import re

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "src/live/config.rs"
EXACT = ROOT / "snapshots/live_bot_exact_equity.md"
HOF = ROOT / "HALL_OF_FAME.md"


def const(text: str, name: str) -> str:
    m = re.search(rf"pub const {name}:\s*(?:usize|f64)\s*=\s*([0-9.]+);", text)
    return m.group(1) if m else "???"


def metric(md: str, label: str) -> str:
    m = re.search(rf"\| {re.escape(label)} \| ([^|]+)\|", md)
    if not m:
        raise SystemExit(f"missing metric: {label}")
    return m.group(1).strip()


def main() -> None:
    cfg = CONFIG.read_text()
    md = EXACT.read_text()
    params = {
        "TURTLE_EP": const(cfg, "TURTLE_EP"),
        "TURTLE_ATR_PERIOD": const(cfg, "TURTLE_ATR_PERIOD"),
        "TURTLE_ATR_MULT": const(cfg, "TURTLE_ATR_MULT"),
        "ATR_ENTRY_MULT": const(cfg, "ATR_ENTRY_MULT"),
        "HOLD_MAX": const(cfg, "HOLD_MAX"),
        "POSITION_CAP": const(cfg, "POSITION_CAP"),
        "REGIME_ATR_PERIOD": const(cfg, "REGIME_ATR_PERIOD"),
        "REGIME_LOOKBACK": const(cfg, "REGIME_LOOKBACK"),
        "ATR_RANK_THRESHOLD": const(cfg, "ATR_RANK_THRESHOLD"),
        "VOL_LOOKBACK": const(cfg, "VOL_LOOKBACK"),
        "HEDGE_ATR_PCT": const(cfg, "HEDGE_ATR_PCT"),
        "HEDGE_SIZE_MULT": const(cfg, "HEDGE_SIZE_MULT"),
    }
    days = metric(md, "Days")
    final_eq = metric(md, "Final equity")
    ann = metric(md, "Annualised return")
    sharpe = metric(md, "Daily account Sharpe")
    maxdd = metric(md, "Max drawdown")
    trades = metric(md, "Trades")
    win = metric(md, "Win rate")
    top5 = metric(md, "Top 5 share of log return")
    top10 = metric(md, "Top 10 share of log return")
    no_top10 = metric(md, "Equity without top 10 log contributors")

    content = f"""# HALL_OF_FAME.md — Proven Strategies

_Auto-generated by `python3 scripts/gen_hof.py` on {dt.date.today().isoformat()}._
_Do not hand-edit headline metrics. Production numbers come from `snapshots/live_bot_exact_equity.md` only._

---

## PRODUCTION CANDIDATE — EXACT LIVE BOT

### Turtle ATR live bot, as coded in `src/live/bot.rs`

**Production source of truth:** `examples/live_bot_exact_equity.rs` replaying the exact live daily event logic with economic mark-to-market account accounting.

| Metric | Value |
|---|---:|
| Universe | Base5 aligned daily bars: BTC, ETH, SOL, XRP, DOGE, ADA |
| Days | {days} |
| Final equity | {final_eq} |
| Annualised return | {ann} |
| Daily account Sharpe | {sharpe} |
| Max drawdown | {maxdd} |
| Trades | {trades} |
| Win rate | {win} |

**Deployability verdict:** viable for dry-run/testnet evaluation, not yet production capital. The current live-coded bot is modest but real-looking: {final_eq} with Sharpe {sharpe} and {maxdd} MaxDD. It is not the old research headline.

### Exact live parameters

```text
TURTLE_EP         = {params['TURTLE_EP']}
TURTLE_ATR_PERIOD = {params['TURTLE_ATR_PERIOD']}
TURTLE_ATR_MULT   = {params['TURTLE_ATR_MULT']}
ATR_ENTRY_MULT    = {params['ATR_ENTRY_MULT']}
HOLD_MAX          = {params['HOLD_MAX']}
POSITION_CAP      = {params['POSITION_CAP']}
REGIME_ATR_PERIOD = {params['REGIME_ATR_PERIOD']}
REGIME_LOOKBACK   = {params['REGIME_LOOKBACK']}
ATR_RANK_THRESHOLD= {params['ATR_RANK_THRESHOLD']}
VOL_LOOKBACK      = {params['VOL_LOOKBACK']}   # configured for diagnostics; intentionally unused by src/live/bot.rs entry logic after T72 rejection
HEDGE_ATR_PCT     = {params['HEDGE_ATR_PCT']}
HEDGE_SIZE_MULT   = {params['HEDGE_SIZE_MULT']}
fee_pct           = 0.000400
```

### Critical reconciliation

- **Exact live bot:** {final_eq} / Sharpe {sharpe} / MaxDD {maxdd} / {trades} trades — production-facing headline.
- **Research harness:** 176.79x / Sharpe 3.29 / MaxDD 99.5% / 156 trades — diagnostic only, not live-coded production performance.
- **T69 semantic-alignment candidate:** 1.02x / Sharpe 0.10 / MaxDD 30.8% — rejected; do not patch live semantics toward that candidate.
- **T72 VOL_LOOKBACK-only live-semantics candidate:** 1.01x / Sharpe 0.09 / MaxDD 30.1% / 207 trades — rejected; do not add a top-3 dollar-volume gate to `src/live/bot.rs`.
- Old `Turtle+Chandelier`, `ATR_RANK=24`, and walk-forward-Sharpe headlines are stale or non-production unless explicitly labelled as diagnostics.

### Fragility / top-trade dependence

| Metric | Value |
|---|---:|
| Equity without top 10 log contributors | {no_top10} |
| Top 5 share of log return | {top5} |
| Top 10 share of log return | {top10} |

Trend-following convexity is material. T73 top-winner conditions audit is the next required guardrail before any new filter work.

---

## RESEARCH DIAGNOSTICS — NOT PRODUCTION HEADLINES

These may guide research, but must not be quoted as live-bot account performance:

| Diagnostic | Status |
|---|---|
| 176.79x research equity | Non-production harness; MaxDD 99.5%; semantic/accounting gap unresolved |
| Walk-forward Sharpe 5+ / 7+ | Per-window comparison metric only; not daily account Sharpe |
| Turtle+Chandelier dual-exit daily curves | Not the current exact `src/live/bot.rs` path |
| VOL_LOOKBACK rank-gated live candidate | Rejected by T72; rank gate alone collapses exact-live equity to 1.01x |
| ATR_RANK=24 / T=65 variants | Failed held-out or superseded; do not report as production |
| HEDGE_ATR_PCT overlay | Inert/dead-code risk overlay in current tested path |

---

## BORDERLINE / PARKED

- **A/D Dual-Hat:** signal exists but standalone pass rate too weak for production.
- **DDBudget 3-Sleeve:** milestone-aggregated metrics are not comparable to daily account Sharpe.
- **Cross-market Turtle variants:** useful robustness evidence, not crypto live-bot deployment candidates.

---

## DECOMMISSIONED

See `GRAVEYARD.md` for full list. Key invalidations:

| Strategy / claim | Why invalid |
|---|---|
| EP=24 | In-sample inflation; held-out confirmed EP=21 |
| ATR_ENTRY_MULT>0 | Entry-side ATR filtering degrades robustness |
| Weekend entry filter | Rejected; weekend entries are valuable |
| T69 semantic alignment patch | Worsened exact live replay to 1.02x |
| VOL_LOOKBACK live top-3 rank gate | Worsened exact live replay to 1.01x |
| Funding-rate regime filter | Rejected / no robust improvement |
| High ATR_RANK thresholds | Non-stationary; held-out failure |

---

## Authoritative files

| File | Contents |
|---|---|
| `examples/live_bot_exact_equity.rs` | Exact live-bot account replay harness |
| `snapshots/live_bot_exact_equity.md` | Production headline metrics |
| `snapshots/live_bot_exact_equity.csv` | Daily equity curve |
| `snapshots/live_bot_exact_trades.csv` | Trade ledger |
| `reports/daily_progress.csv` | Production-only daily tracking after T67 cleanup |
| `charts/live_bot_exact_equity.png` | Log-equity + linear drawdown chart |
"""
    HOF.write_text(content)
    print(f"✓ wrote {HOF}")
    print(f"  exact live: {final_eq} / Sharpe {sharpe} / MaxDD {maxdd} / {trades} trades")


if __name__ == "__main__":
    main()
