# The configuration file for Krypto using the RMatrix algorithm.

# apiKey: None

# apiSecret: None

# The list of tickers that should be traded. These are the options the algorithm has to trade AND the data that will be
# used to train the algorithm. The data is pulled from Binance.
# Default: "BTCBUSD", "ETHBUSD", "BNBBUSD", "ADABUSD",
tickers:
  - "BTCBUSD"
  - "ETHBUSD"
  - "BNBBUSD"
  - "ADABUSD"

# The depth of the R-Matrix. This refers to how many previous periods are used to predict and the maximum number of
# periods that can possibly be predicted forward.
# Default: 5
depth: 5

# The fee that is charged for each trade. This is a percentage of the total amount traded.
# Default: 0.001 (0.1%)
fee: 0.001

# The margin that is used for each trade. This is the leverage that is used for each trade.
# Default: 3 (10x)
margin: 3

# The maximum number of periods that can be predicted forward.
# Default: 2
forwardDepth: 2

# The interval of the data. This refers to the time period of each candlestick. The options are 1m, 3m, 5m, 15m, 30m, 1h,
# Default: 15m
interval: "15m"

# The number of periods to use collect. This refers to how many periods of data are used to train the algorithm.
# Default: 10000
periods: 10000

# Train/Test Split. This refers to the percentage of the data that is used for training. The rest is used for testing.
# Default: 0.8
trainTestSplit: 0.8

# The normalization function used to normalize the data. The options are "Softsign", "Tanh", "Gudermannian", "Algebraic Sigmoid",
# Default: "Softsign"
functionType: "Softsign"

# The goal of the CMA-ES algorithm. This refers to the goal the algorithm is trying to achieve. The options are "accuracy", "error" and "cash"
# Default: "cash"
cmaesGoal: "cash"

# Whether to optimize individual relationships or just the forward depth.
withIndividuals: false
