name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Clippy
      run: rustup component add clippy

    - name: Build and Run Clippy
      run: |
        cargo build --verbose
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --verbose --jobs 8

    - name: Build Artifact
      run: cargo build --release --package krypto

    - name: Create Artifact Directory
      run: mkdir artifacts

    - name: Move Artifact
      run: mv target/release/krypto artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: krypto
        path: artifacts/krypto


